title: Study Notes
description: Personal Study Notes and Documentation
theme: minima
markdown: kramdown
permalink: /:title/

# Social links
github_username: devTabasco

# Build settings
plugins:
  - jekyll-feed 