name: Build HTML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Convert Markdown to HTML
      run: |
        mkdir -p posts_html
        for f in posts/*.md; do
          name=$(basename "$f" .md)
          pandoc "$f" \
            --standalone \
            --template=template.html \
            --css=/assets/css/style.css \
            --metadata title="$(head -n 1 "$f" | sed 's/^# //')" \
            -o "posts_html/$name.html"
        done

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: '.github,posts/*.md' 